config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  #get 'welcome/index'
  #get 'special',to: 'welcome#index' #esto es un hash que hace que cuando se llama a la ruta special responde 'welcome#index'
  
  resources :articles  #crea todo el CRUD de articles  
=begin 
  	get "/articles", to: "articles#index", as: "articles"	index
  	post "/articles" 			create 
  	delete "/articles/:id" destroy			delete
  	get "/articles/:id" 		show
  	get "/articles/new"			new
  	get "/articles/:id/edit"	edit
  	patch "/articles/:id"		update
  	put "/articles/:id"  		update
=end

  post '/articles/new'

  post 'welcome/index' #solo se podra accerder si un link_to llama por post protege la aplicación a recargas de la pagina por el usuario 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #para hacer que la root principal la primera pagina que se abre sea welcome/index
  root 'welcome#index'
  
  
  #root 'views#index' #aqui esta el controlador de la peticion json de Wialon

  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	#model
	#Esta es la clase modelo de articulos
	#la tabla => articles
	#campos article.title() => 'El titulo del articulo'
	#Excribir metodos
	validates :title,presence: true,uniqueness: true
	validates :body,presence: true, length: {minimum: 20}

	#validates :username, format: {with: /regex/}
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#GET /articles
	def index
		#select all
		@articles = Article.all#llama todos los registros de la tabla article
	end	

	#GET /articles/:id
	def show				
		@article = Article.find(params[:id])
		#params es un hash con todos los parametros que se mandaron al servidor web

		#find devuelve siempre el primero
		#Article.where("id = ? ",params[:id])
		#Article.where("id = #{params[:id]}" )#interpolar la cadena es inseguro ya que la vuelve subseptible a sql inyection
		#Article.where("id = ? OR title = ? ",params[:id],params[:title])
	end


	#GET /articles/new
	def new
		@article = Article.new
	end
	#POST /articles
	def create
		#Insert into
		@article= Article.new(article_params)
		
		if @article.save
				
			redirect_to articles_path # redirecciona al index de article
		else
			render :new
		end
		#redirect_to @article #redirecciona al articulo recien creado
			
			#index()			#el uso de estos dos metodos permite
			#render :index	#la llamada al controlador index y la carga de su vistak
		#@article= Article.new(title: params[:article][:title],body: params[:article][:body])		
		#@article= Article.new(params[:article]) no es recomendable ya que no es seguro		
		#@article.invalid?
	end

	#PUT /articles/:id
	def update
		#@article.update_attibutes({title: 'Nuevo titulo'})
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
		end
	end

	def edit
		@article = Article.find(params[:id])
		
	end
	
	def destroy
		@article = Article.find(params[:id])
		@article.destroy #Elimina el objeto de la base de datos
		redirect_to articles_path
	end


	private #todo debajo de esto son metodos privados de la clase

	def article_params#para que se mas segura la insercion de datos
		params.require(:article).permit(:title,:body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :id)
    end
end

app/controllers/views_controller.rb
class ViewsController < ActionController::Base
	def index
		token = "406fc051649392f7aeb828ccb869e6f9804CDB21AA24841B37019B30D22D008766C54B6C"

		@wialon = Wialon.new() #nueva variable Wialon

		@response = @wialon.login(token)
		return render json: @response
		#return render json: Time.new(2018,1,10,16,20,0,"-05:00").strftime('%s')

		params={itemId:15943354,#se necesita un id valido para la peticion de mensajes
				timeFrom: 1515619200,
				timeTo:	1531257600,
				
				flags:(1+0),
				flagsMask:0,
			 	loadCount:99}

		@messages= @wialon.messages_load_interval(params)		

		@response=[]

		@messages['messages'].each do |message|
			#return render json: {}
			@response.push(message)
		end

		#return render json: @messages

=begin
		params = {"spec":{
							itemsType: "avl_unit",	
							propName: "sys_name",
					        propValueMask: "*",
					        sortType: "sys_name"	
			     		},
					    force: 1,			
					    flags:(1 + 4096 + 8), #flags 1:base, 4096:sensors, 8:custom_fields		
			       		from: 0,			
				    	to: 0
					   }

 		@units = @wialon.core_search_items(params)

		@response = []
		
		@units['items'].each do |unit|
			return render json: {units: @units, unit: unit}
			@response.push(unit['nm'])
		end
=end
		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.slim
-name ||= "Crear"
h1
	=name
	| Articulo
= form_for(@article) do |f|
		-@article.errors.full_messages.each do |message|
			.red-white.more-margin
				="*#{message}"
		.field.more-margin
	    	= f.text_field :title ,placeholder: "Título del Artículo",class:"form-control"
	  	.field.text-article.more-margin
			= f.text_area :body ,placeholder: "Escribe aquí el artículo",class:"form-control text-area-new"
		.field.more-margin
			= f.submit "Guardar",class:"btn btn-lg btn-dark"

app/views/articles/edit.html.slim
/articles/edir
.container
	=render "form",name:"Editar "

app/views/articles/index.html.slim
=link_to "Nuevo artículo",articles_new_path,class:"btn btn-primary"
- @articles.each do |article|
	h1= article.title
  	div
    	p
  			=article.body  
  			=link_to " Ver " ,article,class:"btn btn-large btn-primary"
  			=link_to " Editar " ,edit_article_path(article),class:"btn btn-large btn-success"
  			=link_to " Eliminar " ,article,method: :delete,class:"btn btn-large btn-danger"      		

  			/= link_to 'Ver',article_path  #es enviando a su show
			
  			/-paramet={"id" => article.id ,
      					/"format"=> "show"}
			/-@article=article #se vuelve de clase para poder realizar crud despues			

app/views/articles/new.html.slim
/articles/new
.container	
	=render "form",name: "Crear "
	

app/views/articles/show.html.slim
h1= @article.title
div
  p
    = @article.body
	=link_to " Editar " ,edit_article_path(@article),class:"btn btn-large btn-success"    
    =link_to "Eliminar", @article,method: :delete,class:" btn btn-danger"

app/views/layouts/application.html.slim
doctype html
html lang="es"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Blog
    /! este archivo es una plantilla que se repite por toda la pagina web
    /! abajo de mi estan los link añadidos para este projecto
    /fuente roboto
    link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" 

    /script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.16/vue.js"
    
    /! aquí se pueden poner links de fuentes entre otras cosas para que lo tengan todas las vistas
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
  body
    header
      nav.red-white.row.container.col-md-12
        ul.navbar.nav.col-md-12
          h1.no_margin.col-md-3 Blog Cool
          li.col-md-2
            = link_to "Inicio",root_path
          li.col-md-2
            =link_to "Articulos",articles_path
          li.col-md-2
            =link_to "Usuarios",users_path
  = yield 
  == yield :scripts

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :id
    = f.text_field :id
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Name
      th Id
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.id
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Id:
  = @user.id

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path

app/views/welcome/index.html.slim
.container
	h1 Bienvenidos a nuestra pagina
	.card.custom_p	
		- [1,2,3,4].each do |number|
		  	p
				| Número: #{number}
		- mundo = "Luis"
		= "Hola #{mundo}"
		= link_to "Recurso con POST","/welcome/index",method: :post
		

	#app
		p the dude below me is being called by axios :O
		br
		p v-text="status"
/se incluye el javascript por archivo
/== javascript_include_tag 'nombre_del_archivo'

//se incluye el javacript por codigo fuente
/javascript:

== content_for :scripts do
	javascript:
		
		$(document).ready(function(){
			var vm= new Vue({
				el:'#app',
				data: {
					status:'Hello world'
				},
				created: function(){
					this.go();
				},
				methods: {
					go: function(){
						this.status= "Loading...";
						var vm=this;
						axios.get('http://ron-swanson-quotes.herokuapp.com/v2/quotes')//best api ever
						.then(function(response){
							vm.status= response.data[0];
						})
						.catch(function(error){
							vr.status="An error Ocurred: "+error;
						});
					}
				}
			});
			//console.log("Hola")		
		})